export * from './CalcPage'
export * from './ErrorPage'
export * from './GalleryPage'
export * from './MainPage'
export * from './AuthorizationPage'
export * from './RegistrationPage'
export * from './UsPage'
export * from './RelaxPage'
